apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: elontusk404/products-fastapi:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: products-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: products-secrets
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: products-secrets
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: products-secrets
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: products-secrets
              key: DB_NAME
        - name: RABBITMQ
          valueFrom:
            secretKeyRef:
              name: products-secrets
              key: RABBITMQ
        - name: PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: products-secrets
              key: PUBLIC_KEY
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10  
          periodSeconds: 30        
          timeoutSeconds: 5       
          failureThreshold: 3      
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5   
          periodSeconds: 10        
          timeoutSeconds: 5        
          failureThreshold: 3      